########################################################################
## make-hdl © 2025 by Jordan Woods is licensed under CC BY-NC-SA 4.0. ##
## To view a copy of this license, visit                              ##
## https://creativecommons.org/licenses/by-nc-sa/4.0/                 ##
########################################################################
HAS_TC          = yes
TC              = tc1
include ../lib_tb_a/tb_a.mk
include regression_list.mk
include ../../make-hdl/questa/questa.mk
